services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/front
    ports:
      - "3000:3000"
    restart: always
    container_name: "frontend"
    command: >
      npm run dev
    depends_on:
      - web

  web:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    restart: always
    container_name: "backend"
    volumes:
      - .:/code
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PYTHONPATH=/code/src
    command: >
      sh -c "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    container_name: "database"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'

  redis:
    image: redis:7.0.5-alpine
    container_name: "redis"
    restart: always
    hostname: redis
    command: redis-server
    ports:
      - '6379:6379'